project:
  type: book

book:
  title: "R for Plant Nutrition Research"
  author: "T.S. Murrell"
  date: "12/15/2023"
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  freeze: auto

