project:
  type: book

book:
  title: "r4pnr"
  author: "Norah Jones"
  date: "12/15/2023"
  chapters:
    - index.qmd
    - ackknowledgements.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  freeze: auto

