project:
  type: book

book:
  title: "R for Plant Nutrition Research"
  reader-mode: TRUE
  
  page-footer: 
    left: |
      R for Plant Nutrition Research was written by T.S. Murrell, Ph.D.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: cover.png
  favicon: cover.png
  site-url: https://apnicode.github.io/r4pnr/
  repo-url: https://github.com/apnicode/r4pnr/
  
  author:
    - name: "T.S. Murrell, Ph.D."
      id: TSM
      orcid: 0000-0002-8213-0815
      email: s.murrell@apni.net
      corresponding: TRUE
      affiliations:
        - ref: APNI
        - ref: UM6P
        - ref: Purdue
  date: "12/15/2023"
  
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
affiliations:
  - id: APNI
    name: African Plant Nutrition Institute
    address: UM6P Experimental Farm
    city: Benguérir
    postal-code: 43150
    country: Morocco
    url: https://www.apni.net/
  - id: UM6P
    name: Université Mohammed VI Polytechnique
    department: ESAFE
    address: Lot 660, Hay Moulay Rachid
    city: Benguérir
    postal-code: 43150
    country: Morocco
    url: https://um6p.ma/en/school-agriculture-fertilization-and-environmental-sciences
  - id: Purdue
    name: Purdue University
    department: Department of Agronomy
    address: 915 Mitch Daniels Blvd
    city: West Lafayette
    state: IN
    postal-code: 47907
    country: United States
    url: https://ag.purdue.edu/department/agry/

bibliography: references.bib

format:
  html:
    theme:
      light: pulse
      dark: superhero
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  freeze: auto

