project:
  type: book

book:
  title: "R for Plant Nutrition Research"
  author:
    - name: "T.S. Murrell"
      id: TSM
      orcid: 0000-0002-8213-0815
      email: s.murrell@apni.net
      corresponding: TRUE
      affiliations:
        - ref: APNI
        - ref: UM6P
        - ref: Purdue
  date: "12/15/2023"
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
affiliations:
  - id: APNI
    name: African Plant Nutrition Institute
    address: UM6P Experimental Farm
    city: Benguérir
    postal-code: 43150
    country: Morocco
    url: https://www.apni.net/
  - id: UM6P
    name: Université Mohammed VI Polytechnique
    department: ESAFE
    address: Lot 660, Hay Moulay Rachid
    city: Benguérir
    postal-code: 43150
    country: Morocco
    url: https://um6p.ma/en/school-agriculture-fertilization-and-environmental-sciences
  - id: Purdue
    name: Purdue University
    department: Department of Agronomy
    address: 915 Mitch Daniels Blvd
    city: West Lafayette
    state: IN
    postal-code: 47907
    country: United States
    url: https://ag.purdue.edu/department/agry/

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  freeze: auto

